(function(){
 const B=window.BlessERP=window.BlessERP||{},api=()=>B.sriApi;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={BORRADOR:'Borrador',VALIDADO:'Validado',XML_GENERADO:'XML generado',FIRMADO:'Firmado',ENVIADO_SRI:'Enviado al SRI',RECIBIDO_SRI:'Recibido por el SRI',AUTORIZADO:'Autorizado',ANULADO:'Anulado',DEVUELTO:'Devuelto',NO_AUTORIZADO:'No autorizado',PENDIENTE_REINTENTO:'Pendiente de reintento',ERROR_ENVIO:'Error de envío',TRANSPORT_RESULT_UNCERTAIN:'Resultado de envío incierto',AUTHORIZATION_LOOKUP_FIRST:'Consultar autorización primero',MANUAL_REVIEW_REQUIRED:'Revisión manual requerida',WAIT_SCHEDULED:'Espera programada',RETRY_BUDGET_EXHAUSTED:'Intentos automáticos agotados',PROCESSING:'En proceso',FAILED:'Fallido',COMPLETED:'Completado',RETRY_SCHEDULED:'Reintento programado',NO_ENCONTRADO:'No encontrado en autorización',NONE:'Sin trámite',CANCELLATION_REQUESTED:'Anulación solicitada',PENDING_CANCELLATION:'Anulación pendiente',ANNULLED:'Anulado oficialmente'};
 Object.assign(labels,{TRANSMISSION_ATTEMPT:'Intento de transmisión',PAUSE:'Reintentos automáticos pausados',RESUME:'Reintentos automáticos reanudados',CORRECT:'Campos fuente corregidos',EXTERNAL_EVIDENCE:'Evidencia externa verificada',SRI_MANAGER_SOURCE_CORRECTED:'Nueva versión del comprobante',SRI_MANUAL_AUTHORIZATION_CLAIMED:'Consulta manual iniciada',SRI_MANUAL_AUTHORIZATION_EXPIRED:'Consulta manual vencida',SRI_MANUAL_AUTHORIZATION_SETTLED:'Consulta manual finalizada',DISPONIBLE:'Disponible',SIN_ENVIO:'Sin envío',PENDING:'Pendiente',STARTED:'Iniciado',REGISTRADO:'Registrado'});
 const name=v=>labels[v]||v||'—',time=v=>v?new Intl.DateTimeFormat('es-EC',{timeZone:'America/Guayaquil',dateStyle:'short',timeStyle:'medium'}).format(new Date(v)):'—';
 let state={company:'',filters:{environment:'PRODUCTION'},rows:[],total:0,offset:0,selected:null,tab:'summary',validation:null,error:'',busy:false,loaded:false},host=null,app=null,epoch=0;
 let eligibilityTimer=null;
 const activeView=()=>host?.isConnected&&app?.currentRoute==='sri-document-manager'&&(()=>{try{return api().managerCompany().companyId===state.company;}catch{return false;}})();
 function scheduleEligibility(){clearTimeout(eligibilityTimer);const until=state.selected?.managerPolicy?.waitUntil;if(!until||!activeView())return;const token=epoch,id=state.selected.document.id;eligibilityTimer=setTimeout(()=>{if(token===epoch&&activeView()&&state.selected?.document.id===id&&!state.busy)open(id);},Math.min(2147483000,Math.max(5000,Date.parse(until)-Date.now()+1000)));}
 const request=(action,data={},method='GET')=>api().managerRequest('manager-'+action,data,method);
 const input=(key,label,type='text')=>`<label>${esc(label)}<input type="${type}" name="${key}" value="${esc(state.filters[key]||'')}" autocomplete="off"></label>`;
 const select=(key,label,options)=>`<label>${esc(label)}<select name="${key}"><option value="">Todos</option>${options.map(([v,t])=>`<option value="${v}" ${state.filters[key]===v?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
 const field=(label,value)=>`<div><small>${esc(label)}</small><div>${esc(value||'—')}</div></div>`;
 function action(key,label){const p=state.selected?.managerPolicy?.actions?.[key];return `<button type="button" data-action="${key}" ${state.busy||!p?.allowed?'disabled':''} title="${esc(p?.reason||'')}">${esc(label)}</button>`;}
 function renderDetail(){const v=state.selected;if(!v)return '<p>Seleccione un comprobante para consultar su estado y acciones.</p>';const d=v.document,p=v.managerPolicy;
 const tabs=[['summary','Resumen'],['validation','Validación'],['recovery','Recuperación / gestión'],['history','Historial técnico'],['xml','XML / versiones']];
 let body='';
 if(state.tab==='summary')body=`<div class="form-grid">${field('Empresa',api().managerCompany().commercialName)}${field('Ambiente',d.environment==='PRODUCTION'?'PRODUCCIÓN':'TEST')}${field('Tipo',d.document_type)}${field('Número',d.full_number)}${field('Emisión',d.issue_date)}${field('Cliente / proveedor',d.buyer_snapshot?.legalName)}${field('Estado ERP',name(d.status))}${field('Estado SRI',name(v.responses?.[0]?.sri_status))}${field('Último intento',time(v.transmissionAttempts?.[0]?.finished_at||v.transmissionAttempts?.[0]?.created_at))}${field('Intentos registrados',String(v.transmissionAttempts?.length||0))}${field('Próxima consulta',time(p.waitUntil))}${field('Número de autorización',d.authorization_number)}${field('Fecha de autorización',time(d.authorized_at))}${field('Transmisión',name(p.transmissionState))}${field('Reintentos',name(p.retryState))}${field('Recuperación',name(p.recoveryState))}${field('Pedido origen',v.source?.orderId)}${field('Compra origen',v.source?.purchaseId||v.cancellation?.purchaseId)}${field('Factura origen NC',v.source?.originalInvoiceId)}</div><p><strong>Clave de acceso</strong><br>${esc(d.access_key)}</p><p>${esc(d.last_error||'')}</p><ul>${(v.officialMessages||[]).map(m=>`<li>${esc(m.code)} ${esc(m.message)} ${esc(m.additionalInformation)}</li>`).join('')}</ul>`;
 if(state.tab==='validation'){const r=state.validation;body=`<p>La validación no guarda XML, firma ni transmite al SRI.</p>${action('validate','Validar comprobante')}${r?`<h3>${r.validation}</h3><ul>${r.checks.map(c=>`<li>${esc(c.name)}: ${c.result}</li>`).join('')}</ul><ul>${r.errors.map(e=>`<li>${esc(e.check)}: ${esc(e.message)}</li>`).join('')}</ul><ul>${r.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`:''}`;}
 if(state.tab==='recovery')body=`<p>${esc(p.message)}</p>${p.waitUntil?`<p>Próxima consulta: ${esc(time(p.waitUntil))}. Espere ${Math.max(1,Math.ceil((Date.parse(p.waitUntil)-Date.now())/60000))} minutos.</p>`:''}<p>${p.automaticBudgetExhausted?'El límite automático está agotado. La consulta manual conserva su propia elegibilidad.':''}</p><div class="toolbar">${action('recover','Consultar / recuperar SRI')}${action('retry','Reintentar envío')}${action('pause','Pausar reintentos automáticos')}${action('resume','Reanudar automático')}${action('correct','Corregir comprobante')}${action('evidence','Registrar / verificar gestión externa')}</div><p>Las acciones se evalúan en el servidor para este documento.</p>${renderCancellation(v)}`;
 if(state.tab==='history')body=`<div class="table-wrap"><table><thead><tr><th>Fecha Ecuador</th><th>Evento</th><th>Actor</th><th>Resultado / detalle</th><th>Operación / intento</th></tr></thead><tbody>${v.technicalHistory.map(e=>`<tr><td>${esc(time(e.timestamp))}</td><td>${esc(name(e.action))}</td><td>${esc(e.actor||'Sistema')}</td><td>${esc(name(e.result))} ${esc(e.reason)} ${esc(e.classification||'')}</td><td>${esc(e.operationId||'')}<br>${esc(e.attemptId||'')}</td></tr>`).join('')}</tbody></table></div>`;
 if(state.tab==='xml')body=`<p>Versión actual: ${esc(v.management.revision||1)}. Archivos inmutables; sin edición libre de XML.</p><p>Versión 1: archivos originales conservados.</p>${(v.managerEvents||[]).filter(e=>e.action==='CORRECT').map(e=>`<details><summary>Versión ${esc(e.evidence?.revision)} · ${esc(time(e.created_at))}</summary><p>Actor: ${esc(e.actor_user_id)} · Motivo: ${esc(e.reason)}</p><pre>${esc(JSON.stringify(Object.fromEntries(Object.entries(e.evidence?.fields||{}).map(([key,value])=>[key,{anterior:key==='buyerAddress'?e.before_state?.buyer_snapshot?.address:e.before_state?.source_snapshot?.additionalInformation?.Observaciones,nuevo:value}])),null,2))}</pre><p>Los archivos y hashes anteriores permanecen asociados a esta revisión.</p></details>`).join('')}<table><thead><tr><th>Archivo</th><th>Fecha</th><th>SHA-256</th><th></th></tr></thead><tbody>${(v.files||[]).map(f=>`<tr><td>${esc(f.file_type)}</td><td>${esc(time(f.created_at))}</td><td><small>${esc(f.content_sha256)}</small></td><td><button type="button" data-file="${esc(f.id)}">Descargar</button>${f.content_type?.includes('xml')?`<button type="button" data-inspect="${esc(f.id)}">Inspeccionar</button>`:''}</td></tr>`).join('')}</tbody></table><pre data-xml-view style="white-space:pre-wrap;max-height:32rem;overflow:auto"></pre>`;
 return `<section class="card"><div class="toolbar"><h2>${esc(d.full_number)}</h2><button type="button" data-refresh-detail>Actualizar estado</button></div><nav class="toolbar">${tabs.map(([key,label])=>`<button type="button" data-tab="${key}" aria-pressed="${state.tab===key}">${label}</button>`).join('')}</nav>${body}</section>`;
 }
 function renderCancellation(v){const c=v.cancellation;if(!c)return v.document.status==='AUTORIZADO'?'<p>Anulación: consulte el trámite oficial en SRI en Línea. No se cambiará el estado fiscal mediante texto libre.</p>':'';const texts={DISCARD:'Descartar retención',REQUEST:'Solicitar anulación',SUBMIT_PORTAL_REFERENCE:'Registrar solicitud en SRI',CONFIRM_OFFICIAL_ANNULMENT:'Registrar anulación oficial',REISSUE:'Volver a retener desde Compras'};return `<h3>${c.trackingOnly?'Seguimiento de anulación':'Anulación de retención'}</h3><p>${esc(name(c.state))} ${esc(c.unavailableReason||'')}</p>${(c.actions||[]).map(a=>`<button type="button" data-cancel="${a}" ${state.busy?'disabled':''}>${texts[a]||esc(a)}</button>`).join('')}<p>La solicitud no anula el documento. Se conserva la autorización original hasta confirmar evidencia oficial.</p>`;}
 function paint(){if(!activeView())return;host.innerHTML=`<div class="sri-manager"><section class="card"><h1>Gestor de comprobantes electrónicos</h1><p>${esc(api().managerCompany().commercialName||state.company)} · Hora fiscal Ecuador</p><form data-manager-filters><div class="form-grid">${select('environment','Ambiente',[['PRODUCTION','Producción'],['TEST','Test']])}${select('documentType','Tipo',[['01','Factura'],['04','Nota de crédito'],['07','Retención']])}${input('series','Serie')}${input('sequential','Secuencial')}${input('accessKey','Clave de acceso')}${select('status','Estado ERP',Object.entries(labels).filter(([k])=>['BORRADOR','VALIDADO','XML_GENERADO','FIRMADO','ENVIADO_SRI','RECIBIDO_SRI','AUTORIZADO','ANULADO','DEVUELTO','NO_AUTORIZADO','PENDIENTE_REINTENTO','ERROR_ENVIO'].includes(k)))}${select('sriStatus','Estado SRI',[['AUTORIZADO','Autorizado'],['NO_ENCONTRADO','No encontrado'],['DEVUELTA','Devuelto'],['RECIBIDA','Recibido'],['NO AUTORIZADO','No autorizado']])}${select('group','Mostrar',[['PENDING','Pendientes'],['ERRORS','Errores'],['AUTHORIZED','Autorizados']])}${input('party','Cliente / proveedor')}${input('from','Desde','date')}${input('to','Hasta','date')}</div><button ${state.busy?'disabled':''}>Buscar</button></form>${state.error?`<p role="alert">${esc(state.error)}</p>`:''}<p>${state.busy?'Consultando…':`${state.total} comprobantes`}</p><div class="table-wrap"><table><thead><tr><th>Comprobante</th><th>Emisión</th><th>Tipo / ambiente</th><th>Cliente / proveedor</th><th>Estado</th><th></th></tr></thead><tbody>${state.rows.map(d=>`<tr><td>${esc(d.full_number)}</td><td>${esc(d.issue_date)}</td><td>${esc(d.document_type)} / ${esc(d.environment)}</td><td>${esc(d.buyer_snapshot?.legalName)}</td><td>${esc(name(d.status))}</td><td><button type="button" data-document="${esc(d.id)}" ${state.busy?'disabled':''}>Ver / gestionar</button></td></tr>`).join('')}</tbody></table></div><div class="toolbar"><button type="button" data-page="-1" ${state.offset===0||state.busy?'disabled':''}>Anterior</button><button type="button" data-page="1" ${state.offset+50>=state.total||state.busy?'disabled':''}>Siguiente</button></div></section>${renderDetail()}</div>`;bind();scheduleEligibility();}
 async function task(fn){if(state.busy||!activeView())return;const current=epoch;state.busy=true;state.error='';paint();try{await fn(current);}catch(e){if(current===epoch)state.error=e.message;}finally{if(current===epoch){state.busy=false;paint();}}}
 async function load(){return task(async id=>{const r=await request('list',{...state.filters,offset:state.offset});if(id!==epoch)return;state.rows=r.rows;state.total=r.total;state.loaded=true;});}
 async function open(id){return task(async token=>{const d=await request('detail',{documentId:id});if(token!==epoch)return;state.selected=d;state.validation=null;});}
 async function perform(key){if(!state.selected)return;const id=state.selected.document.id;if(['pause','resume','correct','evidence'].includes(key))return showForm(key);await task(async token=>{const r=await request(key,{documentId:id},'POST');if(token!==epoch)return;if(key==='validate')state.validation=r;else state.selected=r;});}
 function showForm(kind){const form=document.createElement('dialog');form.className='sri-manager-dialog';form.innerHTML=`<form method="dialog"><h3>${esc({pause:'Pausar automático',resume:'Reanudar automático',correct:'Corregir campos fuente',evidence:'Verificar gestión externa'}[kind])}</h3><label>Motivo<textarea name="reason" required minlength="3" maxlength="500"></textarea></label>${kind==='correct'?(state.selected.document.document_type==='07'?'':'<label>Dirección del comprador<input name="buyerAddress" maxlength="300"></label>')+'<label>Observaciones<input name="notes" maxlength="300"></label><p>La identidad, fecha, importes e impuestos permanecen protegidos.</p>':''}${kind==='evidence'?'<label>Clave de acceso<input name="accessKey" required pattern="[0-9]{49}"></label><label>Número de autorización<input name="authorizationNumber" required pattern="[0-9]{49}"></label><label>XML oficial (opcional)<input type="file" name="file" accept=".xml"></label><p>Se consultará al SRI; adjuntar un archivo no autoriza el comprobante.</p>':''}<button value="cancel" formnovalidate>Cancelar</button><button value="apply">Confirmar</button></form>`;document.body.append(form);form.showModal();const target=state.selected;form.addEventListener('close',async()=>{const values=new FormData(form.querySelector('form'));form.remove();if(form.returnValue!=='apply'||state.selected!==target)return;const data={documentId:target.document.id,operationId:crypto.randomUUID(),version:target.management.version,documentUpdatedAt:target.document.updated_at,reason:values.get('reason')};if(kind==='correct')data.fields=Object.fromEntries(['buyerAddress','notes'].filter(k=>values.get(k)).map(k=>[k,values.get(k)]));if(kind==='evidence'){data.accessKey=values.get('accessKey');data.authorizationNumber=values.get('authorizationNumber');const f=values.get('file');if(f?.size){if(f.size>2*1024*1024){state.error='El XML supera 2 MB.';paint();return;}data.officialXml=await f.text();}}await task(async token=>{const r=await request(kind,data,'POST');if(token===epoch){state.selected=r;state.validation=null;}});},{once:true});}
 function bind(){host.querySelector('[data-manager-filters]')?.addEventListener('submit',e=>{e.preventDefault();state.filters=Object.fromEntries(new FormData(e.target));state.offset=0;load();});host.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>{state.tab='summary';open(b.dataset.document);});host.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;paint();});host.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>perform(b.dataset.action));host.querySelector('[data-refresh-detail]')?.addEventListener('click',()=>open(state.selected.document.id));host.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.offset=Math.max(0,state.offset+Number(b.dataset.page)*50);load();});host.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>api().managerDownload(b.dataset.file).catch(e=>{state.error=e.message;paint();}));host.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=async()=>{try{const token=epoch,id=state.selected.document.id;const r=await request('download',{fileId:b.dataset.inspect});const content=await r.text();if(token===epoch&&activeView()&&state.selected?.document.id===id&&state.tab==='xml')host.querySelector('[data-xml-view]').textContent=content;}catch(e){state.error=e.message;paint();}});host.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancellationForm(b.dataset.cancel));}
 function cancellationForm(action){if(action==='REISSUE'){B.state?.setRoute?.('purchases-withholdings-issued');return;}const c=state.selected.cancellation,target=state.selected;const dialog=document.createElement('dialog');dialog.className='sri-manager-dialog';dialog.innerHTML=`<form method="dialog"><h3>${esc(action==='DISCARD'?'Descartar retención':'Gestión de anulación SRI')}</h3><label>Motivo<textarea name="reason" required minlength="3"></textarea></label>${action!=='REQUEST'&&action!=='DISCARD'?'<label>Clave de acceso<input name="accessKey" required pattern="[0-9]{49}"></label><label>Referencia oficial<input name="reference" required minlength="3" maxlength="500"></label>':''}${action==='CONFIRM_OFFICIAL_ANNULMENT'?'<label>Número de autorización<input name="authorizationNumber" required pattern="[0-9]{49}"></label><label>Fecha de anulación<input name="annulmentDate" type="date" required></label><label>Constancia oficial<input name="file" type="file" required accept="application/pdf,image/png,image/jpeg"></label><label><input type="checkbox" name="verified" required> Verifiqué ANULADO en SRI en Línea para esta clave</label>':''}<button value="cancel" formnovalidate>Cancelar</button><button value="apply">Confirmar</button></form>`;document.body.append(dialog);dialog.showModal();dialog.addEventListener('close',async()=>{const f=new FormData(dialog.querySelector('form'));dialog.remove();if(dialog.returnValue!=='apply'||state.selected!==target)return;const evidence=Object.fromEntries(['accessKey','reference','authorizationNumber','annulmentDate'].filter(k=>f.get(k)).map(k=>[k,f.get(k)]));if(action==='CONFIRM_OFFICIAL_ANNULMENT'){const file=f.get('file');if(!file||file.size>2*1024*1024){state.error='Constancia inválida o mayor a 2 MB.';paint();return;}const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);Object.assign(evidence,{fileBase64:btoa(binary),contentType:file.type,officialStatus:'ANULADO',verifiedInSriOnline:f.get('verified')==='on'});}await task(async token=>{const r=await request('cancel',{documentId:target.document.id,cancellationAction:action,operationId:crypto.randomUUID(),version:c.version,documentUpdatedAt:c.documentUpdatedAt,reason:f.get('reason'),evidence},'POST');if(token===epoch)state.selected=r;});},{once:true});}
 function render(container,route,appState){const entering=!container.querySelector('[data-manager-filters]');host=container;app=appState;if(entering){epoch++;state.loaded=false;state.busy=false;}let company;try{company=api().managerCompany().companyId;}catch(error){container.textContent=error.message;return;}if(state.company!==company){epoch++;state={company,filters:{environment:'PRODUCTION'},rows:[],total:0,offset:0,selected:null,tab:'summary',validation:null,error:'',busy:false,loaded:false};}paint();if(!state.loaded&&!state.busy)load();}
 B.modules=B.modules||{};B.modules.sriDocumentManager={render};
 B.sriDocumentManagerTest={name,time};
})();
